version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
  build:
    commands:
      - ls -la ${CODEBUILD_SRC_DIR_dev}
      - echo ${ENV_PIPELINE_NAME}
      - echo ${ENV_BRANCH}
      - source ${CODEBUILD_SRC_DIR_dev}/config.env
      - env
#      - . ${CODEBUILD_SRC_DIR}/assume-role.sh ${ENV_PIPELINE_EXECUTION_ROLE} deploy
      - sam deploy -t ${CODEBUILD_SRC_DIR}/codepipeline.yaml --stack-name workflow-${ENV_BRANCH}-${ENV_PIPELINE_NAME} --capabilities=CAPABILITY_IAM --parameter-overrides ParameterKey=SubFolderName,ParameterValue=workflow-${branch}-lambda-${ENV_PIPELINE_NAME} ParameterKey=ResourceType,ParameterValue=${ENV_RESOURCE_TYPE} ParameterKey=CodeStarConnectionArn,ParameterValue=${ENV_CODESTAR_CONNECTION_ARN}
